'use strict';
export const slebyKapovyTopol = [
    {
        id: 1,
        name: "Слэб капового тополя сухой (№K_001)",
        nameCode: "№K_001",
        price: 650,
        height: 350,
        widthMin: 0,
        widthMax: 90,
        thickness: 6,
        linkFullsize: "img/category_kapovy_topol/full/kapovy_topol_001.jpg",
        linkResize: "img/category_kapovy_topol/resize/kapovy_topol_001.jpg",
        description:""
    },
    {
        id: 2,
        name: "Слэб капового тополя сухой (№K_002)",
        nameCode: "№K_002",
        price: 650,
        height: 300,
        widthMin: 0,
        widthMax: 90,
        thickness: 6,
        linkFullsize: "img/category_kapovy_topol/full/kapovy_topol_002.jpg",
        linkResize: "img/category_kapovy_topol/resize/kapovy_topol_002.jpg",
        description:""
    },
    {
        id: 3,
        name: "Слэб капового тополя сухой (№K_003)",
        nameCode: "№K_003",
        price: 600,
        height: 280,
        widthMin: 0,
        widthMax: 85,
        thickness: 6,
        linkFullsize: "img/category_kapovy_topol/full/kapovy_topol_003.jpg",
        linkResize: "img/category_kapovy_topol/resize/kapovy_topol_003.jpg",
        description:""
    },
    {
        id: 4,
        name: "Слэб капового тополя сухой (№K_004)",
        nameCode: "№K_004",
        price: 500,
        height: 220,
        widthMin: 0,
        widthMax: 70,
        thickness: 6,
        linkFullsize: "img/category_kapovy_topol/full/kapovy_topol_004.jpg",
        linkResize: "img/category_kapovy_topol/resize/kapovy_topol_004.jpg",
        description:""
    },
    {
        id: 5,
        name: "Слэб капового тополя сухой (№K_005)",
        nameCode: "№K_005",
        price: 600,
        height: 290,
        widthMin: 0,
        widthMax: 85,
        thickness: 6,
        linkFullsize: "img/category_kapovy_topol/full/kapovy_topol_005.jpg",
        linkResize: "img/category_kapovy_topol/resize/kapovy_topol_005.jpg",
        description:""
    },
    {
        id: 6,
        name: "Слэб капового тополя сухой (№K_006)",
        nameCode: "№K_006",
        price: 600,
        height: 285,
        widthMin: 0,
        widthMax: 85,
        thickness: 6,
        linkFullsize: "img/category_kapovy_topol/full/kapovy_topol_006.jpg",
        linkResize: "img/category_kapovy_topol/resize/kapovy_topol_006.jpg",
        description:""
    },
    {
        id: 7,
        name: "Слэб капового тополя сухой (№K_007)",
        nameCode: "№K_007",
        price: 500,
        height: 310,
        widthMin: 0,
        widthMax: 65,
        thickness: 6,
        linkFullsize: "img/category_kapovy_topol/full/kapovy_topol_007.jpg",
        linkResize: "img/category_kapovy_topol/resize/kapovy_topol_007.jpg",
        description:""
    },
    {
        id: 8,
        name: "Слэб капового тополя сухой (№K_008)",
        nameCode: "№K_008",
        price: 600,
        height: 330,
        widthMin: 0,
        widthMax: 86,
        thickness: 6,
        linkFullsize: "img/category_kapovy_topol/full/kapovy_topol_008.jpg",
        linkResize: "img/category_kapovy_topol/resize/kapovy_topol_008.jpg",
        description:""
    },
    /*
    {
        id: 9,
        name: "Слэб капового тополя сухой (№K_009)",
        nameCode: "№K_009",
        price: 600,
        height: 330,
        widthMin: 0,
        widthMax: 86,
        thickness: 6,
        linkFullsize: "img/category_kapovy_topol/full/kapovy_topol_009.jpg",
        linkResize: "img/category_kapovy_topol/resize/kapovy_topol_009.jpg",
        description:""
    },
    */
    {
        id: 10,
        name: "Слэб капового тополя сухой (№K_010)",
        nameCode: "№K_010",
        price: 650,
        height: 350,
        widthMin: 0,
        widthMax: 90,
        thickness: 6,
        linkFullsize: "img/category_kapovy_topol/full/kapovy_topol_010.jpg",
        linkResize: "img/category_kapovy_topol/resize/kapovy_topol_010.jpg",
        description:""
    },
    {
        id: 11,
        name: "Слэб капового тополя сухой (№K_011)",
        nameCode: "№K_011",
        price: 500,
        height: 187,
        widthMin: 0,
        widthMax: 90,
        thickness: 6,
        linkFullsize: "img/category_kapovy_topol/full/kapovy_topol_011.jpg",
        linkResize: "img/category_kapovy_topol/resize/kapovy_topol_011.jpg",
        description:""
    },
    {
        id: 12,
        name: "Слэб капового тополя сухой (№K_012)",
        nameCode: "№K_012",
        price: 650,
        height: 310,
        widthMin: 0,
        widthMax: 90,
        thickness: 6,
        linkFullsize: "img/category_kapovy_topol/full/kapovy_topol_012.jpg",
        linkResize: "img/category_kapovy_topol/resize/kapovy_topol_012.jpg",
        description:""
    },
    {
        id: 13,
        name: "Слэб капового тополя сухой (№K_013)",
        nameCode: "№K_013",
        price: 500,
        height: 230,
        widthMin: 0,
        widthMax: 75,
        thickness: 6,
        linkFullsize: "img/category_kapovy_topol/full/kapovy_topol_013.jpg",
        linkResize: "img/category_kapovy_topol/resize/kapovy_topol_013.jpg",
        description:""
    },
    {
        id: 14,
        name: "Слэб капового тополя сухой (№K_014)",
        nameCode: "№K_014",
        price: 600,
        height: 290,
        widthMin: 0,
        widthMax: 85,
        thickness: 6,
        linkFullsize: "img/category_kapovy_topol/full/kapovy_topol_014.jpg",
        linkResize: "img/category_kapovy_topol/resize/kapovy_topol_014.jpg",
        description:""
    },

];
